### ISSUE TITLE
Improperly formatted ZonedDateTime in ListTransactions API call

### ISSUE THREAD

**Issue by lcheung-at-square** [TrueLayer/truelayer-java#215] opened 2023-08-23 22:23 UTC
**Describe the bug**
The `MerchantAccountsHandler#listTransactions` method is converting the query argument's ZonedDateTime objects to an invalid string format. The current implementation uses the `DateTimeFormatter.ISO_ZONED_DATE_TIME` format, which generates a string like `2023-01-01T01:01:01.000000001+01:00[Europe/Paris]`; however, according to the [API documentation](https://docs.truelayer.com/reference/merchant-account-get-transactions), the string must of the format `YYYY-MM-DDTHH:MM:SS±HHMM`.

When calling the ListTransactions API using the Java SDK, I get the following error:

> Invalid value for parameter from: invalid `from` query param, status=400, traceId=31df24cb-5781-4c2e-8ee1-faa75d72ab87, errors={"from":["invalid `from` query param"]} 

**To Reproduce**
1. Use the Java SDK to send a ListTransactions request to any merchant account.

**Expected behavior**
I expect the `from` and `to` API parameters to be populated with correctly formatted string representations of ZonedDateTime objects.

**Screenshots**

**Environment (please complete the following information):**
- OS: Oracle Linux Server 8.8
- JVM distribution: JDK 17.0.3
- Library version: 9.0.0

**Additional context**

**Comment by lcheung-at-square** [comment] 2023-08-23 22:32
Looking at the Java 17 docs, the `ISO_OFFSET_DATE_TIME` predefined formatter is more appropriate than the `ISO_ZONED_DATE_TIME` formatter.

**Comment by dili91** [comment] 2023-08-24 10:05
Thanks for raising this. I think the reason why this is currently not catched by our acceptance tests is that we built the `from` param this way:
 `ZonedDateTime from = ZonedDateTime.parse("2021-03-01T00:00:00Z");`

By using the the `now()` and `plus*()` methods offered by the ZonedDataTime api I was able to reproduce this.

I've raised a PR and I'm looking for internal reviews. In the meantime, if you want to give the prerelease a try you can use this snapshot version: `9.0.1-ewt-328-datetime-bugfix-SNAPSHOT`

**Comment by dili91** [comment] 2023-08-24 10:54
I've merged the related PR, feel free to reopen this if you see something unexpected.

**Closed** 2023-08-24 10:54 UTC
Labels: bug
